services:
  redis:
    image: redis:alpine
    ports:
      - "6379:6379"
  app:
    build:
      context: .
      dockerfile: ./docker/development/Dockerfile
    env_file: ./docker/development/.env
    ports:
      - "9292:9292"
    depends_on:
      - redis
    volumes:
      - .:/usr/src/app
    command: bundle exec puma
  test:
    build:
      context: .
      dockerfile: ./docker/test/Dockerfile
    env_file: ./docker/test/.env
    volumes:
      - .:/usr/src/app
    command: bundle exec rspec
